# Generated by Django 5.2.8 on 2026-05-17 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_teacherclass_testsession_student_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(blank=True, max_length=80)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16)),
                ('access_code', models.CharField(blank=True, max_length=32)),
                ('price_label', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testsession',
            name='exam_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='learning.exampack'),
        ),
        migrations.CreateModel(
            name='ExamPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.exampack')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_pack_items', to='learning.test')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('pack', 'test')},
            },
        ),
        migrations.AddField(
            model_name='testsession',
            name='exam_pack_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='learning.exampackitem'),
        ),
    ]
