# Generated by Django 5.2.8 on 2026-05-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_exampack_testsession_exam_pack_exampackitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=24),
        ),
    ]
