# Generated by Django 5.2.8 on 2026-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampack',
            name='manage_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='manage_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='test',
            name='creator_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='test',
            name='creator_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='test',
            name='manage_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='testsession',
            name='student_code',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
