# Generated by Django 5.2.8 on 2026-05-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_exampack_manage_code_teacherclass_manage_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity_code', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('active_role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('school', 'School'), ('creator', 'Creator'), ('admin', 'Admin')], default='student', max_length=24)),
                ('available_roles', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
