# Generated by Django 5.2.8 on 2026-05-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_school_schoolteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtestassignment',
            name='allow_late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classtestassignment',
            name='attempt_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classtestassignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classtestassignment',
            name='grading_policy',
            field=models.CharField(choices=[('best', 'Best attempt'), ('latest', 'Latest attempt'), ('first', 'First attempt')], default='best', max_length=24),
        ),
        migrations.AddField(
            model_name='classtestassignment',
            name='mode',
            field=models.CharField(choices=[('session', 'Live session'), ('homework', 'Homework')], default='session', max_length=24),
        ),
        migrations.AddField(
            model_name='classtestassignment',
            name='show_answers_after_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='accent_color',
            field=models.CharField(default='#8fd6bd', max_length=24),
        ),
        migrations.AddField(
            model_name='school',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='portal_domain',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='school',
            name='portal_subdomain',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#151713', max_length=24),
        ),
        migrations.AddField(
            model_name='school',
            name='student_invite_code',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
