# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_classtestassignment_allow_late_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roleprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
