# Generated by Django 5.2.8 on 2026-08-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_code', models.CharField(max_length=80, unique=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['student_code', '-updated_at'], name='progress_student_updated_idx')],
            },
        ),
    ]
