# Generated by Django 5.2.8 on 2026-08-31 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_studentprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='testsession',
            name='session_student_status_idx',
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['topic', 'status', 'created_at'], name='test_topic_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['student_code', 'status', '-submitted_at'], name='session_student_status_idx'),
        ),
    ]
